modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ttt_heroes"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="TTT-Heroes"
description='''
The Terrifying Temmies Heroes Pack!
'''

[[dependencies.ttt_heroes]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
